name = 'demo-system'

[[world]]
name = 'gazebo-world'
    [world.provider.gazebo]
    world-path = 'gazebo/demo_world.sdf'
    plugin-path = 'gazebo/imu_relay/build/'
    gui-config-path = 'gazebo/gui.config'

    [[world.connector]]
    name = "net"

[[machine]]
name = 'renode-machine'
bin = 'freertos/build/sensor-firmware'
    [machine.assets]
    'freertos/sensor_models/wss.py' = '/freertos/sensor_models/wss.py'

    [machine.provider.renode]
    platform-descriptions = [
        'platforms/boards/stm32f4_discovery-kit.repl',
        'freertos/eth.repl',
        'freertos/sensor_models/c_wss.repl',
    ]
    commands = [
        # Disable PHY1 from being probed
        'sysbus.ethernet.phy1 Id1 0',
        'sysbus.ethernet.phy1 Id2 0',
        'sysbus.cpu PerformanceInMips 1',
    ]

    [[machine.connector]]
    name = 'stdout'
    interface = 'sysbus.usart3'
    port = 3456
    emit-config = false

    [[machine.connector]]
    name = "net"
    interface = 'sysbus.ethernet'

[[machine]]
name = 'linux-machine'
    [machine.provider.container]
    context = 'linux'
    image = 'demo-linux'

    [[machine.connector]]
    name = "net"
    interface = 'conductor0'

[[connection]]
name = 'stdout'
type = 'uart'

[[connection]]
name = "net"
type = "network"
