[plugins]
plugins-dir = '/usr/lib/modality-reflector-plugins'

[ingest]
additional-timeline-attributes = [
    "execution_context='demo'",
    "ci_commit='${GIT_COMMIT-local}'",
]

[plugins.ingest.collectors.lttng-live]
additional-timeline-attributes = [
    "platform='linux'",
    "module='actuator'",
]
override-timeline-attributes = [
    "name='linux'",
]

[plugins.ingest.collectors.lttng-live.metadata]
url = 'net://localhost/host/demo-linux/linux'

[plugins.ingest.collectors.trace-recorder-tcp]
additional-timeline-attributes = [
    "platform='FreeRTOS'",
    "module='sensor'",
]

[plugins.ingest.collectors.trace-recorder-tcp.metadata]
startup-task-name = 'init'
user-event-channel = true
remote = "192.0.2.80:8888"
connect-timeout = "60s"
use-timeline-id-channel = true

    [[plugins.ingest.collectors.trace-recorder-tcp.metadata.user-event-fmt-arg-attr-keys]]
    channel = 'comms-tx'
    format-string = '%u %u %d %u'
    attribute-keys = ['type', 'seqnum', 'wheel_speed', 'nonce']

    [[plugins.ingest.collectors.trace-recorder-tcp.metadata.user-event-fmt-arg-attr-keys]]
    channel = 'wheel-speed'
    format-string = '%d'
    attribute-keys = ['wheel_speed']

